# Generated by Django 5.0.1 on 2024-03-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.BinaryField()),
                ('image_url', models.CharField(max_length=512)),
                ('uri', models.CharField(max_length=512)),
                ('external_url', models.CharField(max_length=512)),
                ('href', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json_response', models.CharField(max_length=32768)),
                ('in_library', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=256)),
                ('device_type', models.CharField(max_length=256)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('token_type', models.CharField(max_length=128)),
                ('scope', models.CharField(max_length=128)),
                ('expires_in', models.IntegerField()),
                ('expires_at', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('playable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configurator.playable')),
                ('release_date', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256)),
            ],
            bases=('configurator.playable',),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configurator.playable')),
                ('owner', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('public', models.BooleanField()),
            ],
            bases=('configurator.playable',),
        ),
        migrations.CreateModel(
            name='ShelfSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('col_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurator.playable')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.shelf')),
            ],
        ),
    ]
