# Generated by Django 5.0.6 on 2024-05-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfspot',
            name='associated_key',
            field=models.IntegerField(null=True),
        ),
    ]
