# Generated by Django 5.0.6 on 2024-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_shelfspot_associated_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='VWCSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=128)),
                ('value_str', models.CharField(max_length=1024)),
                ('value_int', models.IntegerField()),
                ('value_float', models.FloatField()),
            ],
        ),
    ]
