# Generated by Django 5.0.6 on 2024-05-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_vwcsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwcsetting',
            name='value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vwcsetting',
            name='value_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vwcsetting',
            name='value_str',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
