# Generated by Django 5.0.6 on 2024-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_alter_vwcsetting_value_float_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vwcsetting',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('value_str__isnull', False), ('value_int__isnull', False), _negated=True), models.Q(('value_str__isnull', False), ('value_float__isnull', False), _negated=True), models.Q(('value_float__isnull', False), ('value_int__isnull', False), _negated=True), _connector='OR'), name='check_values'),
        ),
    ]
