# Generated by Django 5.0.6 on 2025-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_vwcsetting_check_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwcsetting',
            name='value_str',
            field=models.CharField(max_length=1024, null=True, unique=True),
        ),
    ]
