services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - vwc:/data/db
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    networks:
      - shared-network
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWD:-postgres}"
      POSTGRES_DB: "VinylWall"         # Database name (created on startup)
  spotipy:
    image: python:3.12
    restart: always
    container_name: spotipy
    networks:
      - shared-network
#    ports:
#      - "${MUSIC_DAEMON_PORT:-8082}:${MUSIC_DAEMON_PORT:-8082}"
    environment:
      SPOTIPY_CLIENT_ID: "${SPOTIPY_CLIENT_ID}"
      SPOTIPY_CLIENT_SECRET: "${SPOTIPY_CLIENT_SECRET}"
      SPOTIPY_REDIRECT_URI: "${SPOTIPY_REDIRECT_URI}"
    working_dir: /app/
    volumes:
      - ./helper_services:/app/helper_services
      - ./requirements.txt:/app/requirements.txt
    command: >
      sh -c "
      pip install --no-cache-dir -r /app/requirements.txt &&
      gunicorn -b 0.0.0.0:8082 -w 4 helper_services.spotipy_daemon:app
      "
  gpio_listener:
    image: python:3.12
    restart: always
    container_name: gpio_listener
    networks:
      - shared-network
    environment:
      GPIO_CONFIGURATION: "${GPIO_CONFIGURATION}"
      GPIOZERO_PIN_FACTORY: "${GPIOZERO_PIN_FACTORY}"
      BUTTON_ENDPOINT: "http://VWC:${FRONTEND_PORT:-80}/handle_button"
    working_dir: /app/VinylWallConfig
    volumes:
      - ./helper_services:/app/helper_services
      - ./requirements.txt:/app/requirements.txt
      - /sys/class/gpio:/sys/class/gpio
    privileged: true              # Privileged only for real GPIO
    command: >
      sh -c "
      pip install --no-cache-dir -r /app/requirements.txt &&
      python3 helper_services/gpio_listener.py
      "
    depends_on:
      - VWC
  VWC:
    image: python:3.12
#    restart: always
    container_name: VWC
    ports:
      - "8000:8000"
    networks:
      - shared-network
    environment:
      DJANGO_SETTINGS_MODULE: "VinylWallConfig.settings"
      DB_HOST: "postgres"
      DB_PASSWD: "${DB_PASSWD:-postgres}"
      PYTHONPATH: "${PYTHONPATH}:/app/"
      SECRET_KEY: "django-insecure-s38z-xtdti5jpvowkbp*s-px(me95i!4-hqico7ts)q-ggj0xn"
      DEBUG: 1
      DJANGO_ALLOWED_HOSTS: "localhost,0.0.0.0"
      MUSIC_DAEMON_HOST: spotipy
      MUSIC_DAEMON_PORT: 8082
    working_dir: /app/
    volumes:
      - ./:/app/
    command: >
      sh -c "
      pip install --no-cache-dir -r /app/requirements.txt &&
      python /app/manage.py migrate && 
      django-admin loaddata configurator/fixtures/init.json &&
      daphne -b 0.0.0.0 -p 8000 VinylWallConfig.asgi:application
      "
    depends_on:
      - postgres
      - spotipy

volumes:
  vwc:

networks:
  shared-network:
